=== tmorcinek/android-code-generator-plugin/src/main/resources/types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	targetNamespace="http://www.example.org/types" xmlns:tns="http://www.example.org/types" elementFormDefault="qualified">

	<xs:complexType name="method">
		<xs:sequence>
			<xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="type" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required" />
		<xs:attribute name="type" use="optional" />
	</xs:complexType>

	<xs:complexType name="type">
		<xs:sequence>
			<xs:element name="require" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="listener" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="type" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="implements" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="method" type="tns:method" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
<!--				<xs:key name="MethodKey">-->
<!--					-->
<!--				</xs:key>-->
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required" />
		<xs:attribute name="package" use="optional" />
	</xs:complexType>

	<xs:element name="types">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="type" type="tns:type" maxOccurs="unbounded">
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tmorcinek/android-code-generator-plugin/com.morcinek.android.codegenerator.plugin/src/main/resources/types.xml
<?xml version="1.0" encoding="UTF-8"?>
<types xmlns="http://www.example.org/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/types types.xsd ">

	<type name="OnClickListener" package="android.view.View">
		<implements>
			<method name="onClick">
				<parameter type="View" />
			</method>
		</implements>
	</type>
	<type name="OnCheckedChangeListener" package="android.view.CompoundButton">
		<implements>
			<method name="onCheckedChanged">
				<parameter type="CompoundButton" />
				<parameter type="boolean" />
			</method>
		</implements>
	</type>
	<type name="OnSeekBarChangeListener" package="android.widget.SeekBar">
		<implements>
			<method name="onProgressChanged">
				<parameter type="SeekBar" />
				<parameter type="int" />
				<parameter type="boolean" />
			</method>
			<method name="onStartTrackingTouch">
				<parameter type="SeekBar" />
			</method>
			<method name="onStopTrackingTouch">
				<parameter type="SeekBar" />
			</method>
		</implements>
	</type>
	<type name="Button" package="android.widget">
		<require>
			<listener type="OnClickListener" />
		</require>
	</type>
	<type name="CheckBox" package="android.widget">
		<require>
			<listener type="OnCheckedChangeListener" />
		</require>
	</type>
	<type name="Activity" package="android.app" />
	<type name="Bundle" package="android.os" />
	<type name="View" package="android.view" />
	<type name="EditText" package="android.widget" />
	<type name="ListView" package="android.widget" />
	<type name="RelativeLayout" package="android.widget" />
	<type name="LinearLayout" package="android.widget" />
	<type name="TextView" package="android.widget" />
	<type name="ImageView" package="android.widget" />
	<type name="ImageButton" package="android.widget">
		<require>
			<listener type="OnClickListener" />
		</require>
	</type>
	<type name="SeekBar" package="android.widget" >
		<require>
			<listener type="OnSeekBarChangeListener" />
		</require>
	</type>
</types>

=== tmorcinek/android-code-generator-plugin/com.morcinek.android.codegenerator.plugin-test/src/test/resources/types_easy_no_package.xml
<?xml version="1.0" encoding="UTF-8"?>
<types xmlns="http://www.example.org/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/types types.xsd ">
	<type name="Activity" package="android.app" />
	<type name="Bundle" package="android.os" />
	<type name="View" package="android.view" />
	<type name="EditText" package="android.widget" />
	<type name="ListView" package="android.widget" />
	<type name="morcinek.widget.Button" />
	<type name="RelativeLayout" package="android.widget" />
	<type name="LinearLayout" package="android.widget" />
	<type name="TextView" package="android.widget" />
	<type name="ImageView" package="android.widget" />
</types>
